os:
  - linux
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.12"
  - "4"
  - "5"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i 
